### ISSUE TITLE
CicroCore package.json error

### ISSUE THREAD

**Issue by HidemotoNakada** [Circo-dev/Circo#16]
while trying to follow the instruction below, 

```git clone https://github.com/Circo-dev/CircoCore.js.git
cd CircoCore.js
npm install
npm run serve
```

i have encountered the following  error.
```
npm ERR! code EJSONPARSE
npm ERR! file /xxxxxx/CircoCore.js/package.json
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected string in JSON at position 810 while parsing '{
npm ERR! JSON.parse   "name": "circocore",
npm ERR! JSON.parse   "version": "1'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.
```

It is due to duplicated double quote in package.json

```
  "dependencies": {
    "@ygoe/msgpack": "github:tisztamo/msgpack.js",
    "lit-element": "^2.4.0",
    "local-web-server": "4.2.0",
    "three": ">=0.125.0""    <--- HERE
  },
```

**Comment by tisztamo** [comment]
Thanks for the report, now I have fixed in: https://github.com/Circo-dev/Circo.js/commit/4296abc828d67a287b234f905eac74190ecfb217

**Comment by tisztamo** [comment]
@HidemotoNakada There was another issue with THREE.js 0.125.0, I have fixed it in : https://github.com/Circo-dev/Circo.js/commit/87072dba9a8d788f94e973ec72f6235f283dc3c8 The installation process should now lead to a runnable state.
