### ISSUE TITLE
AbstractMsg not defined

### ISSUE THREAD

**Issue by togo59** [Circo-dev/Circo#18]
Following installation tutorial:
`[rpowell@roger-pc Circo]$ julia --project -e 'using Pkg;Pkg.instantiate'
[rpowell@roger-pc Circo]$ bin/circonode.sh --threads 6 --zygote
┌ Info: Exception while assembling custom type: begin
│     #= /home/rogerp/.julia/packages/CircoCore/YT08L/src/msg.jl:5 =#
│     struct Msg_d4h5{TBody} <: AbstractMsg{TBody}
│         #= /home/rogerp/.julia/packages/CircoCore/YT08L/src/msg.jl:6 =#
│         sender::Addr
│         #= /home/rogerp/.julia/packages/CircoCore/YT08L/src/msg.jl:7 =#
│         target::Addr
│         #= /home/rogerp/.julia/packages/CircoCore/YT08L/src/msg.jl:8 =#
│         body::TBody
│         #= /home/rogerp/.julia/packages/CircoCore/YT08L/src/msg.jl:9 =#
│         begin
│             infoton::Circo.InfotonOpt.Infoton
│         end
│     end
│     #= /home/rogerp/.julia/packages/CircoCore/YT08L/src/msg.jl:11 =#
│     Msg_d4h5(sender::Addr, target, body, args...; kwargs...) = begin
│             #= /home/rogerp/.julia/packages/CircoCore/YT08L/src/msg.jl:11 =#
│             Msg_d4h5{typeof(body)}(sender, target, body, (Circo.InfotonOpt.infotoninit)(sender, target, body, args...; kwargs...))
│         end
│     #= /home/rogerp/.julia/packages/CircoCore/YT08L/src/msg.jl:12 =#
│     Msg_d4h5(sender::Actor, target, body, args...; kwargs...) = begin
│             #= /home/rogerp/.julia/packages/CircoCore/YT08L/src/msg.jl:12 =#
│             Msg_d4h5{typeof(body)}(addr(sender), target, body, (Circo.InfotonOpt.infotoninit)(sender, target, body, args...; kwargs...))
│         end
│     #= /home/rogerp/.julia/packages/CircoCore/YT08L/src/msg.jl:13 =#
│     Msg_d4h5
└ end
ERROR: UndefVarError: AbstractMsg not defined
Stacktrace:
  [1] top-level scope
    @ ~/.julia/packages/CircoCore/YT08L/src/msg.jl:5
  [2] eval
    @ ./boot.jl:373 [inlined]
  [3] eval
    @ ./Base.jl:68 [inlined]
  [4] customtype(stack::Plugins.PluginStack, typename::Symbol, abstract_type::Type, params::Vector{Symbol}, target_module::Module; unique_name::Bool)
    @ Plugins ~/.julia/packages/Plugins/Iandn/src/assembled_types.jl:156
  [5] customtype
    @ ~/.julia/packages/Plugins/Iandn/src/assembled_types.jl:148 [inlined]
  [6] generate_types(pluginstack::Plugins.PluginStack; target_module::Module)
    @ CircoCore ~/.julia/packages/CircoCore/YT08L/src/context.jl:49
  [7] CircoCore.CircoContext(; options::Base.Pairs{Symbol, Any, NTuple{8, Symbol}, NamedTuple{(:addmetoroots, :roots, :rootsfilename, :script, :threads, :iszygote, :profilefn, :userpluginsfn), Tuple{Bool, Vector{Any}, Nothing, String, Int64, Bool, typeof(profile), typeof(plugins)}}})
    @ CircoCore ~/.julia/packages/CircoCore/YT08L/src/context.jl:25
  [8] top-level scope
    @ ~/Circo/src/cli/circonode.jl:203
  [9] eval
    @ ./boot.jl:373 [inlined]
 [10] eval(x::Expr)
    @ Base.MainInclude ./client.jl:453
 [11] top-level scope
    @ none:3
`
My set up:
#############################################
`Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7 CPU         980  @ 3.33GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, westmere)
Environment:
  JULIA_NUM_THREADS = 6
  JULIA_EDITOR = code
`

Earlier installation of Circo
#############################################
`[36e45090] + Circo v0.1.2
    Updating `~/.julia/environments/v1.7/Manifest.toml`
  [36e45090] + Circo v0.1.2
  [b491a1cf] + CircoCore v0.2.11
  [231a7ae5] + Plugins v0.5.4
  [6b5504e1] + TypeParsers v2.0.1
`

**Comment by tisztamo** [comment]
Well, I have to publish a new version.

In the meantime it should work when you also check out CircoCore + Plugins and pkg dev them.

I hope this helps, and I will find the time to release soon (I did not thought it has any users. :) ).

**Comment by tisztamo** [comment]
I fear that Circo is not for you then.

I think that you need to avoid allocations to get close to real-time, and Circo cannot do that at the time, because messages are gc-d after delivery. Multithreaded gc is especially problematic in Julia (The benchmark was done with single-threaded schedulers started with Distributed). I plan to make it better in the future by pooling and reusing messages though. Standard I/O may also be problematic, not sure if you need it.

**Comment by tisztamo** [comment]
The new version is out, it should work again

**Comment by togo59** [comment]
Many thanks! 🙂
________________________________
